# -*- coding: utf-8 -*-
"""Meu primeiro Madlib versao completa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-ajgzoDEpnqgRFLNFOj2x2XzTstfVZV
"""

seu_nome = input("Oi, como você gostaria de ser chamado(a)? ")

print(f"\n\nOlá {seu_nome.title()}, seja bem vindo(a) ao meu primeiro Madlib! Para que sua experiência seja a melhor possível peço que você insira respostas que possuam mais de 1 caractere e que não sejam números! Vamos lá?\n ")

while True:
    bebida = input(" Primeiro insira um apelido, se possível cômico, para bebida: ")
    if isinstance(bebida,str) and len(bebida) > 1:
        break
    elif bebida.isdigit(): #Utilizei .isdigit para assegurar que não teria números dentro da resposta
      bebida = False
      print("Entrada inválida. Não insira digitos por favor")
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não contenha números.")

while True:
    banda = input("\n Agora escolha uma banda ou grupo musical que você goste: ")
    if isinstance(banda, str) and len(banda) > 1 and not banda.isspace(): #Enquanto que aqui utilizei .isinstance pois tem bandas que possuem números, como por exemplo "U2", e bandas com nome composto como \
        break                                                             #"Avenged Sevenfold". Caso utilizasse .isdigit, bandas com número não seriam consideradas respostas válidas e caso utilizasse \
    elif banda.isspace():                                                  #.isalpha bandas com nomes compostos também não seriam válidas. Por último o .isspace() é para garantir que a resposta não sejam somente espaços em branco
        print("Entrada inválida. Por favor, não digite apenas espaços em branco")
    else:                                         
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não seja somente números.")

while True:
    cantor_favorito = input("\nQual é o seu cantor ou cantora favorito? ")
    if isinstance(cantor_favorito, str) and len(cantor_favorito) > 1 and not cantor_favorito.isspace():
        break
    elif cantor_favorito.isdigit(): #Uma verificação para garantir que o usuário não utilize apenas dígitos como resposta.
      cantor_favorito = False
      print("Não digite somente números ")
    elif cantor_favorito.isspace():
      print ("Entrada inválida, não digite somente espaços em branco")
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere.")

while True:
    sexo = input("\n  O artista escolhido é homem ou mulher? Insira H para homem e M para mulher ou X para pessoa não-binária : ").lower()
    if sexo == 'h':
        sexo = 'o' #Utilizei esta parte para garantir que o artigo utilizado no madlib seja correspondente ao sexo do cantor(a) ou como ele(a) se identifica.
        break
    elif sexo == 'm':
        sexo = 'a'
        break
    elif sexo == 'x':
        sexo = ''
        break
    else:
        print("Entrada inválida. Por favor, informe H para homem, M para mulher ou X para pessoa não-binária.")

while True:
    parte_do_corpo = input("\n  Escolha uma parte do corpo humano: ")
    if parte_do_corpo.isalpha() and len(parte_do_corpo) > 1: #O método .isalpha foi utilizado para garantir que somente caracteres alfabéticos fossem utilizados na resposta.
        break
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não contenha um número.")

genero_parte_do_corpo = parte_do_corpo[-1]
if genero_parte_do_corpo == 'a': #Novamente, para garantir que o artigo utilizado é correspondente à parte do corpo informada
    genero_parte_do_corpo = 'a'
else:
    genero_parte_do_corpo = 'o'

while True:
    adjetivo_negativo = input("\n  Escolha um adjetivo negativo: ")
    if adjetivo_negativo.isalpha() and len(adjetivo_negativo) > 1: #Utilizei o .isalpha pelo mesmo motivo acima, garantir que não teriam números como resposta.
        break
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não seja um número.")

while True:
    municipio_paraense = input("\n Agora escolha um município paraense: ")
    if isinstance(municipio_paraense, str) and len(municipio_paraense) > 1:
        break
    elif municipio_paraense.isdigit():
      municipio_paraense = False
      print("Não digite apenas números")
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não seja um número.")

while True:
    municipio_paraense2 = input("\n Um segundo município paraense, por favor: ")
    if isinstance(municipio_paraense2, str) and len(municipio_paraense2) > 1 and not municipio_paraense2 == municipio_paraense: #Um teste para assegurar que seja diferente do 1° município
        break
    elif municipio_paraense2 == municipio_paraense:
      print("\n Escolha um município diferente do anterior")
    elif municipio_paraense2.isdigit():
      municipio_paraense2 = False
      print("Não digite apenas números")
    else:
        print("Entrada inválida. Por favor, insira uma resposta com mais de 1 caractere e que não seja um número.")

while True:
    ofensa = input("\n  Prometo que é o ultimo, digite uma ofensa no plural por favor")
    if isinstance(ofensa,str) and len(ofensa) >1 and ofensa.endswith("s"):
      break
    elif not ofensa.endswith("s"):
        print("Por favor, insira uma ofensa no plural.")
    elif ofensa.isdigit():
      ofensa = False
      print("Entrada inválida. Por favor, insira uma resposta que contenha apenas letras.")
    else:
      print("Por favor, insira uma resposta com mais de 1 caractere.")

madlib = (f" Olá {seu_nome.title()}) \,seja bem vindo ao meu primeiro madlib! Para ter uma melhor experiência, por favor não utilize apenas números em suas respostas. Vamos lá?\n\n\n Você conhece \
a história após a queda de Tróia?\n\n    A pilhagem mítica de Troia foi acompanhada por uma grande festa, na qual, como de costume, os gregos encheram a cara com {bebida} \
e destruíram toda a louça. Entretanto, como nem tudo são flores,\n misteriosos invasores do Mar Negro, publicamente conhecidos como  {banda.title()}, se aproveitaram da farra \
e apagaram as luzes gregas. Isso conduziu a um período que ficara conhecido como a Idade das Trevas.\n Quando os gregos finalmente acenderam tudo de novo, por volta de 800 a.C., além \
de terem descoberto que toda a sua louça estava em péssimas condições, ainda descobriram\n que {sexo} {cantor_favorito.title()} tinha se aposentado e as cidades tinham sido completamente destruídas.\n \
Coçando {genero_parte_do_corpo} {parte_do_corpo.casefold()},os arrependidos e {adjetivo_negativo.casefold()} dos gregos iniciaram a reconstrução.\n    A palavra grega para o novo estilo de cidade era polis e durante um longo tempo eles só \
puderam ter uma, já que ninguém conseguia descobrir qual era o plural da palavra.\n\n   Posteriormente descobriram que tinham surgido duas cidades principais dentro de seu território \
- {municipio_paraense.title()} e {municipio_paraense2.title()} -, também conhecidas como Atenas e Esparta, que\n passavam um terço do tempo guerreando contra os persas, um terço do tempo lutando entre si e o resto do \
tempo brigando consigo mesmas.\n \
\
Ao longo dos anos, as duas cidades desenvolveram democracias, que têm origem nas palavras gregas kratos, que significa “governar por”, e demos, que significa povo, ou, “totais \
{ofensa} que se deixam governar por pessoas ainda mais {ofensa}, chamadas políticos”. Isso ainda propiciou a inspiração para o sistema político moderno mais aceito nos dias de \
hoje, a democracia, ou, governo do povo. ")

print(madlib)



